*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:42543 (IPv4)
Extension host agent listening on 42543

[16:20:18] Extension host agent started.
[16:20:18] [127.0.0.1][60610cfc][ManagementConnection] New connection established.
[16:20:18] [127.0.0.1][b8ede9dd][ExtensionHostConnection] New connection established.
[16:20:18] [127.0.0.1][b8ede9dd][ExtensionHostConnection] <3446> Launched Extension Host Process.
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata:true' -O - http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata:true' http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O - http://169.254.169.254/latest/meta-data/instance-id\n' +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s  http://169.254.169.254/latest/meta-data/instance-id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O - http://169.254.169.254/metadata/v1/id\n' +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s  http://169.254.169.254/metadata/v1/id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata-Flavor:Google' -O - http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google' http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[17:06:25] [127.0.0.1][60610cfc][ManagementConnection] The client has reconnected.
[17:06:26] [127.0.0.1][b8ede9dd][ExtensionHostConnection] The client has reconnected.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[17:06:26] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[17:06:26] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[17:06:27] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[17:06:28] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:17:30] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:17:30] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:17:30] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[18:17:31] [127.0.0.1][60610cfc][ManagementConnection] The client has reconnected.
[18:17:32] [127.0.0.1][b8ede9dd][ExtensionHostConnection] The client has reconnected.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:18:35] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[18:34:36] [127.0.0.1][60610cfc][ManagementConnection] The client has reconnected.
[18:34:37] [127.0.0.1][b8ede9dd][ExtensionHostConnection] The client has reconnected.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:37] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:34:38] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[18:55:07] [127.0.0.1][60610cfc][ManagementConnection] The client has reconnected.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:55:08] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateIcon (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32124),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:55:08] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:55:08] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[18:55:08] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[18:55:49] [127.0.0.1][b8ede9dd][ExtensionHostConnection] The client has reconnected.
[19:36:10] [127.0.0.1][60610cfc][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[19:36:10] [127.0.0.1][b8ede9dd][ExtensionHostConnection] <3446> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[19:36:10] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[19:36:15] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[19:36:15] Cancelling previous shutdown timeout
[19:36:16] [127.0.0.1][4658648e][ManagementConnection] New connection established.
[19:36:16] [127.0.0.1][94a3aef9][ExtensionHostConnection] New connection established.
[19:36:16] [127.0.0.1][94a3aef9][ExtensionHostConnection] <16741> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[19:36:18] [Error [CodeExpectedError]: Could not find pty on pty host,    at c._throwIfNoPty (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:36316),    at c.updateTitle (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:23:32064),    at Object.call (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:16:8386),    at u.onPromise (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5851),    at u.onRawMessage (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:5234),    at /home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:15:4520,    at p.invoke (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:145),    at D.deliver (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:2275),    at T.fire (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:11:1853),    at process.Q (/home/ec2-user/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/platform/terminal/node/ptyHostMain.js:9:20703),    at process.emit (node:events:526:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata:true' -O - http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata:true' http://169.254.169.254/metadata/instance?api-version=2019-03-11\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O - http://169.254.169.254/latest/meta-data/instance-id\n' +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s  http://169.254.169.254/latest/meta-data/instance-id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    '\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q  -O - http://169.254.169.254/metadata/v1/id\n' +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    '\t\tcurl --connect-timeout 7 -s  http://169.254.169.254/metadata/v1/id\n' +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/sh" and args [
  '-c',
  'wget --version > /dev/null\n' +
    'if [ $? -eq 0 ]\n' +
    'then\n' +
    "\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata-Flavor:Google' -O - http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    'else\n' +
    '\tcurl --version > /dev/null\n' +
    '\tif [ $? -eq 0 ]\n' +
    '\tthen\n' +
    "\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google' http://metadata.google.internal/computeMetadata/v1/instance/id\n" +
    '\tfi\n' +
    'fi\n' +
    'exit 0'
]
New EH opened, aborting shutdown
[19:41:15] New EH opened, aborting shutdown
